### ISSUE TITLE
soda: wrong data

### ISSUE THREAD

**Issue by hardin47** [datacamp/stats-apps#10]
@ncarchedi   This is my fault.  I just realized that I had changed the soda data away from being significant last week to tell the story more easily.  The actual data are these:

```r
soda <- data.frame(
  drink = c(rep('orange',13),rep('cola',47)),
  location = c(rep('East',6), rep('West',7), rep('East',28), rep('West',19))
   )
```

**Comment by ncarchedi** [comment]
Done!
